kibot:
  version: 1

outputs:
  - name: 'PCB_top_render'
    type: pcbdraw
    options:
      format: png
      show_components: all
  - name: 'Schematic_PDF'
    comment: "Export schematic to PDF"
    type: pdf_sch_print
    options:
      output: "%f-Schematic.pdf"