kibot:
  version: 1

outputs:
  - name: PCB_top_render
    comment: Render PCB top side
    type: pcbdraw
    options:
      format: png
      show_components: all
      output: output/%f_pcb_top.png
  - name: PCB_bottom_render
    comment: Render PCB bottom side
    type: pcbdraw
    options:
      format: png
      show_components: all
      bottom: true
      output: output/%f_pcb_bottom.png
  - name: Schematic_PDF
    comment: Render schematic
    type: pdf_sch_print
    options:
      output: output/%f_schematic.pdf
  - name: Render 3D
    comment: Render 3D
    type: render_3d
    options:
      format: png
      output: output/%f_render_3d.png
  - name: Blender 3D
    comment: Blender 3D
    type: blender_export
    options:
      render_options:
        samples: 10
        no_denoiser: true
      format: png
      outputs:
        - type: render
          outputp: output/%f_blender.png